# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

target 'project-lfg' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project-lfg
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
  pod 'Eureka', "~> 2.0.0-beta.1"
end
